# Generated by Django 5.1.6 on 2025-03-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeststatus',
            options={'verbose_name': 'request status', 'verbose_name_plural': 'request statuses'},
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('proj_start_date', models.DateTimeField(blank=True, null=True, verbose_name='projected start date')),
                ('proj_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='projected completion date')),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.requeststatus')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
