# Generated by Django 5.1.6 on 2025-03-04 22:02

import core.models.request_status
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_requeststatus_options_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=core.models.request_status.RequestStatus.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='core.requeststatus'),
        ),
    ]
