# Generated by Django 5.2 on 2025-04-16 14:41

import core.models.depth
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_owner_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='depth',
            field=models.ForeignKey(default=core.models.depth.Depth.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='core.depth'),
        ),
    ]
