# Generated by Django 5.1.6 on 2025-03-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
