# Generated by Django 5.1.6 on 2025-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_requeststatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sow_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='statement of work approval date'),
        ),
    ]
