# Generated by Django 5.2 on 2025-05-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_request_depth'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='owner',
            name='only_one_fk_non_null',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='team',
        ),
        migrations.AddField(
            model_name='owner',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reception__isnull', False), ('program__isnull', True), ('lab__isnull', True)), models.Q(('reception__isnull', True), ('program__isnull', False), ('lab__isnull', True)), models.Q(('reception__isnull', True), ('program__isnull', True), ('lab__isnull', False)), _connector='OR'), name='only_one_fk_non_null'),
        ),
    ]
