# Generated by Django 5.1.6 on 2025-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_requeststatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sow_approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='statement of work approval date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='proj_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='projected completion date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='proj_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='projected start date'),
        ),
        migrations.AlterModelTable(
            name='request',
            table=None,
        ),
    ]
