# Generated by Django 5.1.6 on 2025-03-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_request_sow_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
    ]
