# Generated by Django 5.2 on 2025-05-15 15:42

import core.models.reception
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(default=core.models.reception.Reception.get_default_pk, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner'),
        ),
    ]
