# Generated by Django 5.1.6 on 2025-03-05 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_request_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('proj_start_date__gte', datetime.date(2025, 3, 5)), ('proj_start_date__isnull', True), _connector='OR'), name='projected_start_date_in_future_or_null', violation_error_message='The projected start date must not be set in the past.'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('proj_completion_date__gte', datetime.date(2025, 3, 5)), ('proj_completion_date__isnull', True), _connector='OR'), name='projected_completion_date_in_future_or_null', violation_error_message='The projected completion date must not be set in the past.'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('proj_completion_date__gt', models.F('proj_start_date')), ('proj_start_date__isnull', True), _connector='OR'), name='projected_completion_date_after_projected_start_date_or_null', violation_error_message='The projected completion date must be after the projected start date'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('proj_start_date__lt', models.F('proj_completion_date')), ('proj_completion_date__isnull', True), _connector='OR'), name='projected_start_date_before_projected_completion_date_or_null', violation_error_message='The projected start date must be before the projected completion date'),
        ),
    ]
