# Generated by Django 5.2 on 2025-05-15 15:55

import core.models.owner
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_owner_request_request_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(blank=True, default=core.models.owner.Owner.get_default_pk, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner'),
        ),
    ]
