# Generated by Django 5.1.6 on 2025-03-07 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_request_projected_start_date_in_future_or_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request',
            name='projected_start_date_in_future_or_null',
        ),
        migrations.RemoveConstraint(
            model_name='request',
            name='projected_completion_date_in_future_or_null',
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('proj_start_date__gte', datetime.date(2025, 3, 7)), ('proj_start_date__isnull', True), _connector='OR'), name='projected_start_date_in_future_or_null', violation_error_message='The projected start date must not be set in the past.'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('proj_completion_date__gte', datetime.date(2025, 3, 7)), ('proj_completion_date__isnull', True), _connector='OR'), name='projected_completion_date_in_future_or_null', violation_error_message='The projected completion date must not be set in the past.'),
        ),
    ]
