# Generated by Django 5.1.6 on 2025-03-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_request_projected_start_date_in_future_or_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request',
            name='projected_start_date_in_future_or_null',
        ),
        migrations.RemoveConstraint(
            model_name='request',
            name='projected_completion_date_in_future_or_null',
        ),
    ]
