# Generated by Django 5.2 on 2025-05-15 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_owner_expert_alter_owner_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='expert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lab'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.program'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='reception',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.reception'),
        ),
    ]
