# Generated by Django 5.1.6 on 2025-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionPlanningRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'transmission_planning_region',
            },
        ),
    ]
