# Generated by Django 5.2 on 2025-05-23 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_programroleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='labroleassignment',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
