# Generated by Django 5.1.6 on 2025-05-29 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_labroleassignment_date_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reception')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reception_role_assignment',
            },
        ),
    ]
