# Generated by Django 5.1.6 on 2025-03-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transmissionplanningregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=64, verbose_name='phone number')),
                ('title', models.CharField(max_length=256, verbose_name='job title')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.state')),
                ('tpr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.transmissionplanningregion', verbose_name='transmission planning region')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
