# Generated by Django 5.1.6 on 2025-03-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='CustomerRequestRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customertype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.request')),
            ],
            options={
                'db_table': 'customer_request_relationship',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='requests',
            field=models.ManyToManyField(related_name='customers', through='core.CustomerRequestRelationship', to='core.request'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestrelationship',
            constraint=models.UniqueConstraint(fields=('customer', 'request'), name='unique_customer_request'),
        ),
    ]
