# Generated by Django 5.1.6 on 2025-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customertype_name_customerrequestrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
