# Generated by Django 5.1.6 on 2025-05-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_availablelabrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableReceptionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
            options={
                'db_table': 'available_reception_role',
            },
        ),
    ]
