# Generated by Django 5.1.6 on 2025-06-02 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.depth')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expertise',
            },
        ),
    ]
