# Generated by Django 5.1.6 on 2025-03-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.request')),
            ],
            options={
                'db_table': 'cohort',
            },
        ),
    ]
