# Generated by Django 5.1.6 on 2025-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='cohort', to='core.customer'),
        ),
    ]
