# Generated by Django 5.1.6 on 2025-03-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cohort_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='depth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.depth'),
            preserve_default=False,
        ),
    ]
