# Generated by Django 5.1.6 on 2025-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_request_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=None, max_length=64, verbose_name='phone number'),
        ),
    ]
