# Generated by Django 5.1.6 on 2025-07-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_receipt_request_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request', to='core.receipt'),
        ),
    ]
