# Generated by Django 5.1.6 on 2025-07-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_receipt_request_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='labs',
            field=models.ManyToManyField(blank=True, related_name='programs', to='core.lab'),
        ),
    ]
