# Generated by Django 5.1.6 on 2025-07-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_program_labs'),
        ('core', '0028_alter_request_receipt'),
    ]

    operations = [
    ]
