# Generated by Django 5.1.6 on 2025-07-17 14:18

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_request_description_alter_request_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='receipt',
            field=models.OneToOneField(default=django.db.models.query.QuerySet.create, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='core.receipt'),
        ),
        migrations.AlterModelTable(
            name='lab',
            table='lab',
        ),
        migrations.AlterModelTable(
            name='program',
            table='program',
        ),
    ]
