# Generated by Django 5.1.6 on 2025-07-29 19:35

import django.db.models.deletion
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_attachment_file_name_alter_request_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='user_who_uploaded',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='receipt',
            field=models.OneToOneField(blank=True, default=django.db.models.query.QuerySet.create, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='core.receipt'),
        ),
    ]
