# Generated by Django 5.1.6 on 2025-08-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_attachment_file_name_attachment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='user_who_uploaded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Add Attachment', 'Addattachment'), ('Remove Attachment', 'Removeattachment'), ('Edit Request Information', 'Editrequestinfo'), ('Edit Customer Information', 'Editcustomerinfo')], max_length=64)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.request')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_history',
            },
        ),
    ]
