# Generated by Django 5.1.6 on 2025-08-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20250811_1844'),
        ('core', '0042_alter_request_receipt_note'),
    ]

    operations = [
    ]
