# Generated by Django 5.1.6 on 2025-08-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_attachment_user_who_uploaded_audithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audithistory',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.request'),
        ),
    ]
