# Generated by Django 5.1.6 on 2025-08-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_audithistory_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audithistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.request'),
        ),
    ]
