# Generated by Django 5.1.6 on 2025-09-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_cohortparticipant'),
        ('core', '0047_program_filtered_orgs'),
    ]

    operations = [
    ]
