# Generated by Django 5.1.6 on 2025-09-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20250915_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request', to='core.receipt'),
        ),
    ]
