# Generated by Django 5.1.6 on 2026-03-30 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_request_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='program',
        ),
        migrations.RemoveField(
            model_name='request',
            name='receipt',
        ),
        migrations.RemoveConstraint(
            model_name='owner',
            name='only_one_fk_non_null',
        ),
        migrations.AddField(
            model_name='owner',
            name='expert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.lab'),
        ),
        migrations.AddField(
            model_name='request',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.program'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='domain_type',
            field=models.CharField(choices=[('reception', 'reception'), ('program', 'program'), ('lab', 'lab'), ('expert', 'expert')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reception__isnull', False), ('program__isnull', True), ('lab__isnull', True), ('expert__isnull', True)), models.Q(('reception__isnull', True), ('program__isnull', False), ('lab__isnull', True), ('expert__isnull', True)), models.Q(('reception__isnull', True), ('program__isnull', True), ('lab__isnull', False), ('expert__isnull', True)), models.Q(('reception__isnull', True), ('program__isnull', True), ('lab__isnull', True), ('expert__isnull', False)), _connector='OR'), name='only_one_fk_non_null'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('lab__isnull', True), ('program__isnull', False), _connector='OR'), name='lab_requires_program', violation_error_message='A program must be assigned before a lab can be assigned'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.CheckConstraint(condition=models.Q(('expert__isnull', True), ('lab__isnull', False), _connector='OR'), name='expert_requires_lab', violation_error_message='A lab must be assigned before an expert can be assigned'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
