# Generated by Django 5.1.6 on 2026-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_receipt_expert_remove_receipt_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='filtered_orgs',
        ),
        migrations.AddField(
            model_name='program',
            name='organization_types',
            field=models.ManyToManyField(blank=True, related_name='programs', to='core.organizationtype'),
        ),
    ]
