# Generated by Django 5.1.6 on 2026-04-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_program_filtered_orgs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseoutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by_lab', models.BooleanField(default=False)),
                ('approved_by_program', models.BooleanField(default=False)),
                ('experience_description', models.TextField(blank=True, null=True, verbose_name='Short description of the experience')),
                ('ta_provided_description', models.TextField(blank=True, null=True, verbose_name='What was provided to meet the request?')),
                ('impact_description', models.TextField(blank=True, null=True, verbose_name='What is the likely impact on the stakeholder?')),
                ('alignment_description', models.TextField(blank=True, null=True, verbose_name='Did the final TA align with the original request?')),
                ('customer_feedback', models.TextField(blank=True, null=True, verbose_name='Any feedback or comments from TA requester?')),
                ('follow_up_needed', models.BooleanField(default=False, verbose_name='Request follow-up/additional TA?')),
                ('follow_up_description', models.TextField(blank=True, null=True, verbose_name='What is the scope of the additional TA effort? (topics, etc.)')),
                ('follow_up_duration', models.CharField(blank=True, max_length=256, null=True, verbose_name='How much additional time is needed?')),
                ('follow_up_comments', models.TextField(blank=True, null=True, verbose_name='Other questions/comments regarding follow-up TA')),
                ('follow_up_has_same_expert', models.BooleanField(default=False, verbose_name='Do you want to be an SME for any follow-up?')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closeout_form', to='core.request')),
            ],
            options={
                'db_table': 'closeout_form',
            },
        ),
    ]
