# Generated by Django 5.1.6 on 2026-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_closeoutform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closeoutform",
            name="follow_up_has_same_expert",
            field=models.BooleanField(
                default=False,
                verbose_name="Do you want to be a subject matter expert (SME) for any follow-up?",
            ),
        ),
        migrations.AlterField(
            model_name="closeoutform",
            name="submitted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
