# Generated by Django 5.1.6 on 2026-05-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_closeoutform_follow_up_has_same_expert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertise",
            name="lab_role_assignment",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.labroleassignment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="labroleassignment",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.program",
            ),
            preserve_default=False,
        ),
    ]
