# Generated by Django 5.1.6 on 2026-06-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_customerrequestrelationship_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='org',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tpr',
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, to='core.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='transmission_planning_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.transmissionplanningregion', verbose_name='transmission planning region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='organization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='core.organization'),
            preserve_default=False,
        ),
    ]
