# Generated by Django 5.1.6 on 2026-06-16 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_customer_org_remove_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.organization'),
        ),
    ]
