# Generated by Django 5.1.6 on 2026-07-27 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_alter_audithistory_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audithistory",
            name="role",
        ),
    ]
