# Generated by Django 5.1.6 on 2026-08-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_audithistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.request'),
        ),
    ]
