/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithNavRouteImport } from './routes/_with-nav/route'
import { Route as IndexImport } from './routes/index'
import { Route as publicIntakeImport } from './routes/(public)/intake'
import { Route as WithNavPublicOnlyRouteImport } from './routes/_with-nav/_public-only/route'
import { Route as WithNavPrivateRouteImport } from './routes/_with-nav/_private/route'
import { Route as WithNavPublicOnlyLoginImport } from './routes/_with-nav/_public-only/login'
import { Route as WithNavPrivateProfileImport } from './routes/_with-nav/_private/profile'
import { Route as WithNavPrivateDashboardRouteImport } from './routes/_with-nav/_private/dashboard/route'
import { Route as WithNavPrivateDashboardExpertsImport } from './routes/_with-nav/_private/dashboard/experts'
import { Route as publicAccountProviderCallbackImport } from './routes/(public)/account.provider.callback'
import { Route as WithNavPrivateDashboardRequestsRouteImport } from './routes/_with-nav/_private/dashboard/requests/route'
import { Route as WithNavPrivateDashboardRequestsIndexImport } from './routes/_with-nav/_private/dashboard/requests/index'
import { Route as WithNavPrivateDashboardRequestsRequestIdImport } from './routes/_with-nav/_private/dashboard/requests/$requestId'

// Create/Update Routes

const WithNavRouteRoute = WithNavRouteImport.update({
  id: '/_with-nav',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const publicIntakeRoute = publicIntakeImport.update({
  id: '/(public)/intake',
  path: '/intake',
  getParentRoute: () => rootRoute,
} as any)

const WithNavPublicOnlyRouteRoute = WithNavPublicOnlyRouteImport.update({
  id: '/_public-only',
  getParentRoute: () => WithNavRouteRoute,
} as any)

const WithNavPrivateRouteRoute = WithNavPrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => WithNavRouteRoute,
} as any)

const WithNavPublicOnlyLoginRoute = WithNavPublicOnlyLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WithNavPublicOnlyRouteRoute,
} as any)

const WithNavPrivateProfileRoute = WithNavPrivateProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WithNavPrivateRouteRoute,
} as any)

const WithNavPrivateDashboardRouteRoute =
  WithNavPrivateDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => WithNavPrivateRouteRoute,
  } as any)

const WithNavPrivateDashboardExpertsRoute =
  WithNavPrivateDashboardExpertsImport.update({
    id: '/experts',
    path: '/experts',
    getParentRoute: () => WithNavPrivateDashboardRouteRoute,
  } as any)

const publicAccountProviderCallbackRoute =
  publicAccountProviderCallbackImport.update({
    id: '/(public)/account/provider/callback',
    path: '/account/provider/callback',
    getParentRoute: () => rootRoute,
  } as any)

const WithNavPrivateDashboardRequestsRouteRoute =
  WithNavPrivateDashboardRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => WithNavPrivateDashboardRouteRoute,
  } as any)

const WithNavPrivateDashboardRequestsIndexRoute =
  WithNavPrivateDashboardRequestsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WithNavPrivateDashboardRequestsRouteRoute,
  } as any)

const WithNavPrivateDashboardRequestsRequestIdRoute =
  WithNavPrivateDashboardRequestsRequestIdImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => WithNavPrivateDashboardRequestsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav': {
      id: '/_with-nav'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavRouteImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav/_private': {
      id: '/_with-nav/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavPrivateRouteImport
      parentRoute: typeof WithNavRouteImport
    }
    '/_with-nav/_public-only': {
      id: '/_with-nav/_public-only'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavPublicOnlyRouteImport
      parentRoute: typeof WithNavRouteImport
    }
    '/(public)/intake': {
      id: '/(public)/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof publicIntakeImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav/_private/dashboard': {
      id: '/_with-nav/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WithNavPrivateDashboardRouteImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/_with-nav/_private/profile': {
      id: '/_with-nav/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WithNavPrivateProfileImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/_with-nav/_public-only/login': {
      id: '/_with-nav/_public-only/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof WithNavPublicOnlyLoginImport
      parentRoute: typeof WithNavPublicOnlyRouteImport
    }
    '/_with-nav/_private/dashboard/requests': {
      id: '/_with-nav/_private/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof WithNavPrivateDashboardRequestsRouteImport
      parentRoute: typeof WithNavPrivateDashboardRouteImport
    }
    '/(public)/account/provider/callback': {
      id: '/(public)/account/provider/callback'
      path: '/account/provider/callback'
      fullPath: '/account/provider/callback'
      preLoaderRoute: typeof publicAccountProviderCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav/_private/dashboard/experts': {
      id: '/_with-nav/_private/dashboard/experts'
      path: '/experts'
      fullPath: '/dashboard/experts'
      preLoaderRoute: typeof WithNavPrivateDashboardExpertsImport
      parentRoute: typeof WithNavPrivateDashboardRouteImport
    }
    '/_with-nav/_private/dashboard/requests/$requestId': {
      id: '/_with-nav/_private/dashboard/requests/$requestId'
      path: '/$requestId'
      fullPath: '/dashboard/requests/$requestId'
      preLoaderRoute: typeof WithNavPrivateDashboardRequestsRequestIdImport
      parentRoute: typeof WithNavPrivateDashboardRequestsRouteImport
    }
    '/_with-nav/_private/dashboard/requests/': {
      id: '/_with-nav/_private/dashboard/requests/'
      path: '/'
      fullPath: '/dashboard/requests/'
      preLoaderRoute: typeof WithNavPrivateDashboardRequestsIndexImport
      parentRoute: typeof WithNavPrivateDashboardRequestsRouteImport
    }
  }
}

// Create and export the route tree

interface WithNavPrivateDashboardRequestsRouteRouteChildren {
  WithNavPrivateDashboardRequestsRequestIdRoute: typeof WithNavPrivateDashboardRequestsRequestIdRoute
  WithNavPrivateDashboardRequestsIndexRoute: typeof WithNavPrivateDashboardRequestsIndexRoute
}

const WithNavPrivateDashboardRequestsRouteRouteChildren: WithNavPrivateDashboardRequestsRouteRouteChildren =
  {
    WithNavPrivateDashboardRequestsRequestIdRoute:
      WithNavPrivateDashboardRequestsRequestIdRoute,
    WithNavPrivateDashboardRequestsIndexRoute:
      WithNavPrivateDashboardRequestsIndexRoute,
  }

const WithNavPrivateDashboardRequestsRouteRouteWithChildren =
  WithNavPrivateDashboardRequestsRouteRoute._addFileChildren(
    WithNavPrivateDashboardRequestsRouteRouteChildren,
  )

interface WithNavPrivateDashboardRouteRouteChildren {
  WithNavPrivateDashboardRequestsRouteRoute: typeof WithNavPrivateDashboardRequestsRouteRouteWithChildren
  WithNavPrivateDashboardExpertsRoute: typeof WithNavPrivateDashboardExpertsRoute
}

const WithNavPrivateDashboardRouteRouteChildren: WithNavPrivateDashboardRouteRouteChildren =
  {
    WithNavPrivateDashboardRequestsRouteRoute:
      WithNavPrivateDashboardRequestsRouteRouteWithChildren,
    WithNavPrivateDashboardExpertsRoute: WithNavPrivateDashboardExpertsRoute,
  }

const WithNavPrivateDashboardRouteRouteWithChildren =
  WithNavPrivateDashboardRouteRoute._addFileChildren(
    WithNavPrivateDashboardRouteRouteChildren,
  )

interface WithNavPrivateRouteRouteChildren {
  WithNavPrivateDashboardRouteRoute: typeof WithNavPrivateDashboardRouteRouteWithChildren
  WithNavPrivateProfileRoute: typeof WithNavPrivateProfileRoute
}

const WithNavPrivateRouteRouteChildren: WithNavPrivateRouteRouteChildren = {
  WithNavPrivateDashboardRouteRoute:
    WithNavPrivateDashboardRouteRouteWithChildren,
  WithNavPrivateProfileRoute: WithNavPrivateProfileRoute,
}

const WithNavPrivateRouteRouteWithChildren =
  WithNavPrivateRouteRoute._addFileChildren(WithNavPrivateRouteRouteChildren)

interface WithNavPublicOnlyRouteRouteChildren {
  WithNavPublicOnlyLoginRoute: typeof WithNavPublicOnlyLoginRoute
}

const WithNavPublicOnlyRouteRouteChildren: WithNavPublicOnlyRouteRouteChildren =
  {
    WithNavPublicOnlyLoginRoute: WithNavPublicOnlyLoginRoute,
  }

const WithNavPublicOnlyRouteRouteWithChildren =
  WithNavPublicOnlyRouteRoute._addFileChildren(
    WithNavPublicOnlyRouteRouteChildren,
  )

interface WithNavRouteRouteChildren {
  WithNavPrivateRouteRoute: typeof WithNavPrivateRouteRouteWithChildren
  WithNavPublicOnlyRouteRoute: typeof WithNavPublicOnlyRouteRouteWithChildren
}

const WithNavRouteRouteChildren: WithNavRouteRouteChildren = {
  WithNavPrivateRouteRoute: WithNavPrivateRouteRouteWithChildren,
  WithNavPublicOnlyRouteRoute: WithNavPublicOnlyRouteRouteWithChildren,
}

const WithNavRouteRouteWithChildren = WithNavRouteRoute._addFileChildren(
  WithNavRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof WithNavPublicOnlyRouteRouteWithChildren
  '/intake': typeof publicIntakeRoute
  '/dashboard': typeof WithNavPrivateDashboardRouteRouteWithChildren
  '/profile': typeof WithNavPrivateProfileRoute
  '/login': typeof WithNavPublicOnlyLoginRoute
  '/dashboard/requests': typeof WithNavPrivateDashboardRequestsRouteRouteWithChildren
  '/account/provider/callback': typeof publicAccountProviderCallbackRoute
  '/dashboard/experts': typeof WithNavPrivateDashboardExpertsRoute
  '/dashboard/requests/$requestId': typeof WithNavPrivateDashboardRequestsRequestIdRoute
  '/dashboard/requests/': typeof WithNavPrivateDashboardRequestsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof WithNavPublicOnlyRouteRouteWithChildren
  '/intake': typeof publicIntakeRoute
  '/dashboard': typeof WithNavPrivateDashboardRouteRouteWithChildren
  '/profile': typeof WithNavPrivateProfileRoute
  '/login': typeof WithNavPublicOnlyLoginRoute
  '/account/provider/callback': typeof publicAccountProviderCallbackRoute
  '/dashboard/experts': typeof WithNavPrivateDashboardExpertsRoute
  '/dashboard/requests/$requestId': typeof WithNavPrivateDashboardRequestsRequestIdRoute
  '/dashboard/requests': typeof WithNavPrivateDashboardRequestsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_with-nav': typeof WithNavRouteRouteWithChildren
  '/_with-nav/_private': typeof WithNavPrivateRouteRouteWithChildren
  '/_with-nav/_public-only': typeof WithNavPublicOnlyRouteRouteWithChildren
  '/(public)/intake': typeof publicIntakeRoute
  '/_with-nav/_private/dashboard': typeof WithNavPrivateDashboardRouteRouteWithChildren
  '/_with-nav/_private/profile': typeof WithNavPrivateProfileRoute
  '/_with-nav/_public-only/login': typeof WithNavPublicOnlyLoginRoute
  '/_with-nav/_private/dashboard/requests': typeof WithNavPrivateDashboardRequestsRouteRouteWithChildren
  '/(public)/account/provider/callback': typeof publicAccountProviderCallbackRoute
  '/_with-nav/_private/dashboard/experts': typeof WithNavPrivateDashboardExpertsRoute
  '/_with-nav/_private/dashboard/requests/$requestId': typeof WithNavPrivateDashboardRequestsRequestIdRoute
  '/_with-nav/_private/dashboard/requests/': typeof WithNavPrivateDashboardRequestsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/intake'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/dashboard/requests'
    | '/account/provider/callback'
    | '/dashboard/experts'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/intake'
    | '/dashboard'
    | '/profile'
    | '/login'
    | '/account/provider/callback'
    | '/dashboard/experts'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests'
  id:
    | '__root__'
    | '/'
    | '/_with-nav'
    | '/_with-nav/_private'
    | '/_with-nav/_public-only'
    | '/(public)/intake'
    | '/_with-nav/_private/dashboard'
    | '/_with-nav/_private/profile'
    | '/_with-nav/_public-only/login'
    | '/_with-nav/_private/dashboard/requests'
    | '/(public)/account/provider/callback'
    | '/_with-nav/_private/dashboard/experts'
    | '/_with-nav/_private/dashboard/requests/$requestId'
    | '/_with-nav/_private/dashboard/requests/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithNavRouteRoute: typeof WithNavRouteRouteWithChildren
  publicIntakeRoute: typeof publicIntakeRoute
  publicAccountProviderCallbackRoute: typeof publicAccountProviderCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithNavRouteRoute: WithNavRouteRouteWithChildren,
  publicIntakeRoute: publicIntakeRoute,
  publicAccountProviderCallbackRoute: publicAccountProviderCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_with-nav",
        "/(public)/intake",
        "/(public)/account/provider/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_with-nav": {
      "filePath": "_with-nav/route.tsx",
      "children": [
        "/_with-nav/_private",
        "/_with-nav/_public-only"
      ]
    },
    "/_with-nav/_private": {
      "filePath": "_with-nav/_private/route.tsx",
      "parent": "/_with-nav",
      "children": [
        "/_with-nav/_private/dashboard",
        "/_with-nav/_private/profile"
      ]
    },
    "/_with-nav/_public-only": {
      "filePath": "_with-nav/_public-only/route.tsx",
      "parent": "/_with-nav",
      "children": [
        "/_with-nav/_public-only/login"
      ]
    },
    "/(public)/intake": {
      "filePath": "(public)/intake.tsx"
    },
    "/_with-nav/_private/dashboard": {
      "filePath": "_with-nav/_private/dashboard/route.tsx",
      "parent": "/_with-nav/_private",
      "children": [
        "/_with-nav/_private/dashboard/requests",
        "/_with-nav/_private/dashboard/experts"
      ]
    },
    "/_with-nav/_private/profile": {
      "filePath": "_with-nav/_private/profile.tsx",
      "parent": "/_with-nav/_private"
    },
    "/_with-nav/_public-only/login": {
      "filePath": "_with-nav/_public-only/login.tsx",
      "parent": "/_with-nav/_public-only"
    },
    "/_with-nav/_private/dashboard/requests": {
      "filePath": "_with-nav/_private/dashboard/requests/route.tsx",
      "parent": "/_with-nav/_private/dashboard",
      "children": [
        "/_with-nav/_private/dashboard/requests/$requestId",
        "/_with-nav/_private/dashboard/requests/"
      ]
    },
    "/(public)/account/provider/callback": {
      "filePath": "(public)/account.provider.callback.tsx"
    },
    "/_with-nav/_private/dashboard/experts": {
      "filePath": "_with-nav/_private/dashboard/experts.tsx",
      "parent": "/_with-nav/_private/dashboard"
    },
    "/_with-nav/_private/dashboard/requests/$requestId": {
      "filePath": "_with-nav/_private/dashboard/requests/$requestId.tsx",
      "parent": "/_with-nav/_private/dashboard/requests"
    },
    "/_with-nav/_private/dashboard/requests/": {
      "filePath": "_with-nav/_private/dashboard/requests/index.tsx",
      "parent": "/_with-nav/_private/dashboard/requests"
    }
  }
}
ROUTE_MANIFEST_END */
