/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithNavRouteImport } from './routes/_with-nav/route'
import { Route as IndexImport } from './routes/index'
import { Route as publicIntakeImport } from './routes/(public)/intake'
import { Route as WithNavPublicOnlyRouteImport } from './routes/_with-nav/_public-only/route'
import { Route as WithNavPrivateRouteImport } from './routes/_with-nav/_private/route'
import { Route as WithNavPublicOnlyLoginImport } from './routes/_with-nav/_public-only/login'
import { Route as WithNavPrivateProfileImport } from './routes/_with-nav/_private/profile'
import { Route as WithNavPrivateExpertsImport } from './routes/_with-nav/_private/experts'
import { Route as WithNavPrivateRequestsIndexImport } from './routes/_with-nav/_private/requests/index'
import { Route as publicAccountProviderCallbackImport } from './routes/(public)/account.provider.callback'
import { Route as WithNavPrivateRequestsInactiveRouteImport } from './routes/_with-nav/_private/requests/inactive/route'
import { Route as WithNavPrivateRequestsActiveRouteImport } from './routes/_with-nav/_private/requests/active/route'
import { Route as WithNavPrivateRequestsInactiveIndexImport } from './routes/_with-nav/_private/requests/inactive/index'
import { Route as WithNavPrivateRequestsActiveIndexImport } from './routes/_with-nav/_private/requests/active/index'
import { Route as WithNavPrivateRequestsInactiveRequestIdImport } from './routes/_with-nav/_private/requests/inactive/$requestId'
import { Route as WithNavPrivateRequestsActiveRequestIdImport } from './routes/_with-nav/_private/requests/active/$requestId'

// Create/Update Routes

const WithNavRouteRoute = WithNavRouteImport.update({
  id: '/_with-nav',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const publicIntakeRoute = publicIntakeImport.update({
  id: '/(public)/intake',
  path: '/intake',
  getParentRoute: () => rootRoute,
} as any)

const WithNavPublicOnlyRouteRoute = WithNavPublicOnlyRouteImport.update({
  id: '/_public-only',
  getParentRoute: () => WithNavRouteRoute,
} as any)

const WithNavPrivateRouteRoute = WithNavPrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => WithNavRouteRoute,
} as any)

const WithNavPublicOnlyLoginRoute = WithNavPublicOnlyLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WithNavPublicOnlyRouteRoute,
} as any)

const WithNavPrivateProfileRoute = WithNavPrivateProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WithNavPrivateRouteRoute,
} as any)

const WithNavPrivateExpertsRoute = WithNavPrivateExpertsImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => WithNavPrivateRouteRoute,
} as any)

const WithNavPrivateRequestsIndexRoute =
  WithNavPrivateRequestsIndexImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => WithNavPrivateRouteRoute,
  } as any)

const publicAccountProviderCallbackRoute =
  publicAccountProviderCallbackImport.update({
    id: '/(public)/account/provider/callback',
    path: '/account/provider/callback',
    getParentRoute: () => rootRoute,
  } as any)

const WithNavPrivateRequestsInactiveRouteRoute =
  WithNavPrivateRequestsInactiveRouteImport.update({
    id: '/requests/inactive',
    path: '/requests/inactive',
    getParentRoute: () => WithNavPrivateRouteRoute,
  } as any)

const WithNavPrivateRequestsActiveRouteRoute =
  WithNavPrivateRequestsActiveRouteImport.update({
    id: '/requests/active',
    path: '/requests/active',
    getParentRoute: () => WithNavPrivateRouteRoute,
  } as any)

const WithNavPrivateRequestsInactiveIndexRoute =
  WithNavPrivateRequestsInactiveIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WithNavPrivateRequestsInactiveRouteRoute,
  } as any)

const WithNavPrivateRequestsActiveIndexRoute =
  WithNavPrivateRequestsActiveIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WithNavPrivateRequestsActiveRouteRoute,
  } as any)

const WithNavPrivateRequestsInactiveRequestIdRoute =
  WithNavPrivateRequestsInactiveRequestIdImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => WithNavPrivateRequestsInactiveRouteRoute,
  } as any)

const WithNavPrivateRequestsActiveRequestIdRoute =
  WithNavPrivateRequestsActiveRequestIdImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => WithNavPrivateRequestsActiveRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav': {
      id: '/_with-nav'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavRouteImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav/_private': {
      id: '/_with-nav/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavPrivateRouteImport
      parentRoute: typeof WithNavRouteImport
    }
    '/_with-nav/_public-only': {
      id: '/_with-nav/_public-only'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavPublicOnlyRouteImport
      parentRoute: typeof WithNavRouteImport
    }
    '/(public)/intake': {
      id: '/(public)/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof publicIntakeImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav/_private/experts': {
      id: '/_with-nav/_private/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof WithNavPrivateExpertsImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/_with-nav/_private/profile': {
      id: '/_with-nav/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WithNavPrivateProfileImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/_with-nav/_public-only/login': {
      id: '/_with-nav/_public-only/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof WithNavPublicOnlyLoginImport
      parentRoute: typeof WithNavPublicOnlyRouteImport
    }
    '/_with-nav/_private/requests/active': {
      id: '/_with-nav/_private/requests/active'
      path: '/requests/active'
      fullPath: '/requests/active'
      preLoaderRoute: typeof WithNavPrivateRequestsActiveRouteImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/_with-nav/_private/requests/inactive': {
      id: '/_with-nav/_private/requests/inactive'
      path: '/requests/inactive'
      fullPath: '/requests/inactive'
      preLoaderRoute: typeof WithNavPrivateRequestsInactiveRouteImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/(public)/account/provider/callback': {
      id: '/(public)/account/provider/callback'
      path: '/account/provider/callback'
      fullPath: '/account/provider/callback'
      preLoaderRoute: typeof publicAccountProviderCallbackImport
      parentRoute: typeof rootRoute
    }
    '/_with-nav/_private/requests/': {
      id: '/_with-nav/_private/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof WithNavPrivateRequestsIndexImport
      parentRoute: typeof WithNavPrivateRouteImport
    }
    '/_with-nav/_private/requests/active/$requestId': {
      id: '/_with-nav/_private/requests/active/$requestId'
      path: '/$requestId'
      fullPath: '/requests/active/$requestId'
      preLoaderRoute: typeof WithNavPrivateRequestsActiveRequestIdImport
      parentRoute: typeof WithNavPrivateRequestsActiveRouteImport
    }
    '/_with-nav/_private/requests/inactive/$requestId': {
      id: '/_with-nav/_private/requests/inactive/$requestId'
      path: '/$requestId'
      fullPath: '/requests/inactive/$requestId'
      preLoaderRoute: typeof WithNavPrivateRequestsInactiveRequestIdImport
      parentRoute: typeof WithNavPrivateRequestsInactiveRouteImport
    }
    '/_with-nav/_private/requests/active/': {
      id: '/_with-nav/_private/requests/active/'
      path: '/'
      fullPath: '/requests/active/'
      preLoaderRoute: typeof WithNavPrivateRequestsActiveIndexImport
      parentRoute: typeof WithNavPrivateRequestsActiveRouteImport
    }
    '/_with-nav/_private/requests/inactive/': {
      id: '/_with-nav/_private/requests/inactive/'
      path: '/'
      fullPath: '/requests/inactive/'
      preLoaderRoute: typeof WithNavPrivateRequestsInactiveIndexImport
      parentRoute: typeof WithNavPrivateRequestsInactiveRouteImport
    }
  }
}

// Create and export the route tree

interface WithNavPrivateRequestsActiveRouteRouteChildren {
  WithNavPrivateRequestsActiveRequestIdRoute: typeof WithNavPrivateRequestsActiveRequestIdRoute
  WithNavPrivateRequestsActiveIndexRoute: typeof WithNavPrivateRequestsActiveIndexRoute
}

const WithNavPrivateRequestsActiveRouteRouteChildren: WithNavPrivateRequestsActiveRouteRouteChildren =
  {
    WithNavPrivateRequestsActiveRequestIdRoute:
      WithNavPrivateRequestsActiveRequestIdRoute,
    WithNavPrivateRequestsActiveIndexRoute:
      WithNavPrivateRequestsActiveIndexRoute,
  }

const WithNavPrivateRequestsActiveRouteRouteWithChildren =
  WithNavPrivateRequestsActiveRouteRoute._addFileChildren(
    WithNavPrivateRequestsActiveRouteRouteChildren,
  )

interface WithNavPrivateRequestsInactiveRouteRouteChildren {
  WithNavPrivateRequestsInactiveRequestIdRoute: typeof WithNavPrivateRequestsInactiveRequestIdRoute
  WithNavPrivateRequestsInactiveIndexRoute: typeof WithNavPrivateRequestsInactiveIndexRoute
}

const WithNavPrivateRequestsInactiveRouteRouteChildren: WithNavPrivateRequestsInactiveRouteRouteChildren =
  {
    WithNavPrivateRequestsInactiveRequestIdRoute:
      WithNavPrivateRequestsInactiveRequestIdRoute,
    WithNavPrivateRequestsInactiveIndexRoute:
      WithNavPrivateRequestsInactiveIndexRoute,
  }

const WithNavPrivateRequestsInactiveRouteRouteWithChildren =
  WithNavPrivateRequestsInactiveRouteRoute._addFileChildren(
    WithNavPrivateRequestsInactiveRouteRouteChildren,
  )

interface WithNavPrivateRouteRouteChildren {
  WithNavPrivateExpertsRoute: typeof WithNavPrivateExpertsRoute
  WithNavPrivateProfileRoute: typeof WithNavPrivateProfileRoute
  WithNavPrivateRequestsActiveRouteRoute: typeof WithNavPrivateRequestsActiveRouteRouteWithChildren
  WithNavPrivateRequestsInactiveRouteRoute: typeof WithNavPrivateRequestsInactiveRouteRouteWithChildren
  WithNavPrivateRequestsIndexRoute: typeof WithNavPrivateRequestsIndexRoute
}

const WithNavPrivateRouteRouteChildren: WithNavPrivateRouteRouteChildren = {
  WithNavPrivateExpertsRoute: WithNavPrivateExpertsRoute,
  WithNavPrivateProfileRoute: WithNavPrivateProfileRoute,
  WithNavPrivateRequestsActiveRouteRoute:
    WithNavPrivateRequestsActiveRouteRouteWithChildren,
  WithNavPrivateRequestsInactiveRouteRoute:
    WithNavPrivateRequestsInactiveRouteRouteWithChildren,
  WithNavPrivateRequestsIndexRoute: WithNavPrivateRequestsIndexRoute,
}

const WithNavPrivateRouteRouteWithChildren =
  WithNavPrivateRouteRoute._addFileChildren(WithNavPrivateRouteRouteChildren)

interface WithNavPublicOnlyRouteRouteChildren {
  WithNavPublicOnlyLoginRoute: typeof WithNavPublicOnlyLoginRoute
}

const WithNavPublicOnlyRouteRouteChildren: WithNavPublicOnlyRouteRouteChildren =
  {
    WithNavPublicOnlyLoginRoute: WithNavPublicOnlyLoginRoute,
  }

const WithNavPublicOnlyRouteRouteWithChildren =
  WithNavPublicOnlyRouteRoute._addFileChildren(
    WithNavPublicOnlyRouteRouteChildren,
  )

interface WithNavRouteRouteChildren {
  WithNavPrivateRouteRoute: typeof WithNavPrivateRouteRouteWithChildren
  WithNavPublicOnlyRouteRoute: typeof WithNavPublicOnlyRouteRouteWithChildren
}

const WithNavRouteRouteChildren: WithNavRouteRouteChildren = {
  WithNavPrivateRouteRoute: WithNavPrivateRouteRouteWithChildren,
  WithNavPublicOnlyRouteRoute: WithNavPublicOnlyRouteRouteWithChildren,
}

const WithNavRouteRouteWithChildren = WithNavRouteRoute._addFileChildren(
  WithNavRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof WithNavPublicOnlyRouteRouteWithChildren
  '/intake': typeof publicIntakeRoute
  '/experts': typeof WithNavPrivateExpertsRoute
  '/profile': typeof WithNavPrivateProfileRoute
  '/login': typeof WithNavPublicOnlyLoginRoute
  '/requests/active': typeof WithNavPrivateRequestsActiveRouteRouteWithChildren
  '/requests/inactive': typeof WithNavPrivateRequestsInactiveRouteRouteWithChildren
  '/account/provider/callback': typeof publicAccountProviderCallbackRoute
  '/requests': typeof WithNavPrivateRequestsIndexRoute
  '/requests/active/$requestId': typeof WithNavPrivateRequestsActiveRequestIdRoute
  '/requests/inactive/$requestId': typeof WithNavPrivateRequestsInactiveRequestIdRoute
  '/requests/active/': typeof WithNavPrivateRequestsActiveIndexRoute
  '/requests/inactive/': typeof WithNavPrivateRequestsInactiveIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof WithNavPublicOnlyRouteRouteWithChildren
  '/intake': typeof publicIntakeRoute
  '/experts': typeof WithNavPrivateExpertsRoute
  '/profile': typeof WithNavPrivateProfileRoute
  '/login': typeof WithNavPublicOnlyLoginRoute
  '/account/provider/callback': typeof publicAccountProviderCallbackRoute
  '/requests': typeof WithNavPrivateRequestsIndexRoute
  '/requests/active/$requestId': typeof WithNavPrivateRequestsActiveRequestIdRoute
  '/requests/inactive/$requestId': typeof WithNavPrivateRequestsInactiveRequestIdRoute
  '/requests/active': typeof WithNavPrivateRequestsActiveIndexRoute
  '/requests/inactive': typeof WithNavPrivateRequestsInactiveIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_with-nav': typeof WithNavRouteRouteWithChildren
  '/_with-nav/_private': typeof WithNavPrivateRouteRouteWithChildren
  '/_with-nav/_public-only': typeof WithNavPublicOnlyRouteRouteWithChildren
  '/(public)/intake': typeof publicIntakeRoute
  '/_with-nav/_private/experts': typeof WithNavPrivateExpertsRoute
  '/_with-nav/_private/profile': typeof WithNavPrivateProfileRoute
  '/_with-nav/_public-only/login': typeof WithNavPublicOnlyLoginRoute
  '/_with-nav/_private/requests/active': typeof WithNavPrivateRequestsActiveRouteRouteWithChildren
  '/_with-nav/_private/requests/inactive': typeof WithNavPrivateRequestsInactiveRouteRouteWithChildren
  '/(public)/account/provider/callback': typeof publicAccountProviderCallbackRoute
  '/_with-nav/_private/requests/': typeof WithNavPrivateRequestsIndexRoute
  '/_with-nav/_private/requests/active/$requestId': typeof WithNavPrivateRequestsActiveRequestIdRoute
  '/_with-nav/_private/requests/inactive/$requestId': typeof WithNavPrivateRequestsInactiveRequestIdRoute
  '/_with-nav/_private/requests/active/': typeof WithNavPrivateRequestsActiveIndexRoute
  '/_with-nav/_private/requests/inactive/': typeof WithNavPrivateRequestsInactiveIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/intake'
    | '/experts'
    | '/profile'
    | '/login'
    | '/requests/active'
    | '/requests/inactive'
    | '/account/provider/callback'
    | '/requests'
    | '/requests/active/$requestId'
    | '/requests/inactive/$requestId'
    | '/requests/active/'
    | '/requests/inactive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/intake'
    | '/experts'
    | '/profile'
    | '/login'
    | '/account/provider/callback'
    | '/requests'
    | '/requests/active/$requestId'
    | '/requests/inactive/$requestId'
    | '/requests/active'
    | '/requests/inactive'
  id:
    | '__root__'
    | '/'
    | '/_with-nav'
    | '/_with-nav/_private'
    | '/_with-nav/_public-only'
    | '/(public)/intake'
    | '/_with-nav/_private/experts'
    | '/_with-nav/_private/profile'
    | '/_with-nav/_public-only/login'
    | '/_with-nav/_private/requests/active'
    | '/_with-nav/_private/requests/inactive'
    | '/(public)/account/provider/callback'
    | '/_with-nav/_private/requests/'
    | '/_with-nav/_private/requests/active/$requestId'
    | '/_with-nav/_private/requests/inactive/$requestId'
    | '/_with-nav/_private/requests/active/'
    | '/_with-nav/_private/requests/inactive/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WithNavRouteRoute: typeof WithNavRouteRouteWithChildren
  publicIntakeRoute: typeof publicIntakeRoute
  publicAccountProviderCallbackRoute: typeof publicAccountProviderCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithNavRouteRoute: WithNavRouteRouteWithChildren,
  publicIntakeRoute: publicIntakeRoute,
  publicAccountProviderCallbackRoute: publicAccountProviderCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_with-nav",
        "/(public)/intake",
        "/(public)/account/provider/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_with-nav": {
      "filePath": "_with-nav/route.tsx",
      "children": [
        "/_with-nav/_private",
        "/_with-nav/_public-only"
      ]
    },
    "/_with-nav/_private": {
      "filePath": "_with-nav/_private/route.tsx",
      "parent": "/_with-nav",
      "children": [
        "/_with-nav/_private/experts",
        "/_with-nav/_private/profile",
        "/_with-nav/_private/requests/active",
        "/_with-nav/_private/requests/inactive",
        "/_with-nav/_private/requests/"
      ]
    },
    "/_with-nav/_public-only": {
      "filePath": "_with-nav/_public-only/route.tsx",
      "parent": "/_with-nav",
      "children": [
        "/_with-nav/_public-only/login"
      ]
    },
    "/(public)/intake": {
      "filePath": "(public)/intake.tsx"
    },
    "/_with-nav/_private/experts": {
      "filePath": "_with-nav/_private/experts.tsx",
      "parent": "/_with-nav/_private"
    },
    "/_with-nav/_private/profile": {
      "filePath": "_with-nav/_private/profile.tsx",
      "parent": "/_with-nav/_private"
    },
    "/_with-nav/_public-only/login": {
      "filePath": "_with-nav/_public-only/login.tsx",
      "parent": "/_with-nav/_public-only"
    },
    "/_with-nav/_private/requests/active": {
      "filePath": "_with-nav/_private/requests/active/route.tsx",
      "parent": "/_with-nav/_private",
      "children": [
        "/_with-nav/_private/requests/active/$requestId",
        "/_with-nav/_private/requests/active/"
      ]
    },
    "/_with-nav/_private/requests/inactive": {
      "filePath": "_with-nav/_private/requests/inactive/route.tsx",
      "parent": "/_with-nav/_private",
      "children": [
        "/_with-nav/_private/requests/inactive/$requestId",
        "/_with-nav/_private/requests/inactive/"
      ]
    },
    "/(public)/account/provider/callback": {
      "filePath": "(public)/account.provider.callback.tsx"
    },
    "/_with-nav/_private/requests/": {
      "filePath": "_with-nav/_private/requests/index.tsx",
      "parent": "/_with-nav/_private"
    },
    "/_with-nav/_private/requests/active/$requestId": {
      "filePath": "_with-nav/_private/requests/active/$requestId.tsx",
      "parent": "/_with-nav/_private/requests/active"
    },
    "/_with-nav/_private/requests/inactive/$requestId": {
      "filePath": "_with-nav/_private/requests/inactive/$requestId.tsx",
      "parent": "/_with-nav/_private/requests/inactive"
    },
    "/_with-nav/_private/requests/active/": {
      "filePath": "_with-nav/_private/requests/active/index.tsx",
      "parent": "/_with-nav/_private/requests/active"
    },
    "/_with-nav/_private/requests/inactive/": {
      "filePath": "_with-nav/_private/requests/inactive/index.tsx",
      "parent": "/_with-nav/_private/requests/inactive"
    }
  }
}
ROUTE_MANIFEST_END */
