name: Backend CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: "backend/api/uv.lock"

      - name: Install dependencies
        working-directory: backend/api
        run: uv sync --locked

      - name: Run Ruff check
        working-directory: backend/api
        run: uv run --locked ruff check .

      - name: Run Ruff format check
        working-directory: backend/api
        run: uv run --locked ruff format --check .

  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: api.settings
      SECRET_KEY: secret_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: "backend/api/uv.lock"

      - name: Install dependencies
        working-directory: backend/api
        run: uv sync --locked

      - name: Run migrations
        working-directory: backend/api
        run: uv run --locked python manage.py migrate

      - name: Run tests with pytest
        working-directory: backend/api
        run: uv run --locked pytest
