name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.9"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend dependencies
        run: pip install -r backend/api/requirements.txt

      - name: Collect static files and migrate database
        run: |
          python backend/api/manage.py collectstatic --noinput
          python backend/api/manage.py migrate

      - name: Deploy backend with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./backend"
          target: "/home/${{ secrets.SSH_USERNAME }}/taconnect-staging/backend"

      - name: Install frontend dependencies
        run: npm install --prefix ./frontend

      - name: Build React app
        run: npm run build --prefix ./frontend

      - name: Deploy frontend with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./frontend/dist"
          target: "/home/${{ secrets.SSH_USERNAME }}/taconnect-staging/frontend/dist"

      - name: Restart application server (optional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
